server:
  port: 8072

spring:
  application:
    name: sky_agent
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sky_agent?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null
  mvc:
    async:
      request-timeout: 300000

mybatis-plus:
  type-aliases-package: com.agent.entity

logging:
  level:
    com.agent: debug

RequestApi:
  url: http://localhost:8000/

external:
  hmdp:
    base-url: http://localhost:8081
  sky-take-out:
    base-url: http://localhost:8086
